### PR TITLE
Spelling correction

### PR DESCRIPTION
**Pull request by saran-sasidharan**
Spelling correction

### CODE REVIEW

**Comment by Butt4cak3** [comment]
The word "efficient" in the same line is spelled wrong, too. You could fix that as well before we merge and we get 2 for 1.

**Comment by saran-sasidharan** [comment]
Thanks @Butt4cak3 . I think i made a mistake of creating several pull request for different edits. I will take care of it future. thanks

**Comment by julianschacher** [comment]
@saran-sasidharan welcome from me as well!

**Comment by saran-sasidharan** [comment]
@julianschacher Thank you :)

**Comment by Butt4cak3** [comment]
@saran-sasidharan Multiple pull requests are not necessarily a bad thing. But when it comes to a bunch of spelling mistakes, it's okay to group them up in one.

**Pull request merged**
