### PR TITLE
Fix Dumb Typos

### PR DESCRIPTION
**Pull request by nikhiljha**
Ran through it with a script and fixed the things the script changed that weren't right. I'm pretty sure I've checked everything but you may want to eyeball the changed to make sure.

*do not merge yet, WIP*

### CODE REVIEW

**Comment by leios** [comment]
Yup, these are all dumb typos. Thanks for catching them!

I cannot believe I misspelled License...

**Comment by nikhiljha** [comment]
Oh boy, the ones I have right now are actually pretty mild. Spicier ones incoming... 😄

**Comment by leios** [comment]
Haha, thanks!

**Comment by nikhiljha** [comment]
And that should be all of them. Feel free to merge when reviewed.

**Comment by leios** [comment]
Looks good to me! I don't know how so many of these get through...

Regardless, thanks a lot!

**Pull request merged**
