### PR TITLE
Add the Prism Syntax Highlighting Plugin

### PR DESCRIPTION
**Pull request by julianschacher**
Add the prism syntax highlighting plugin to the AAA, set its config and modify some import statements.
The plugin on GitBook Plugins: https://plugins.gitbook.com/plugin/prism
Solves #96

### CODE REVIEW

**Comment by leios** [comment]
Cool! I'll build this and check it out when I get home.

**Comment by julianschacher** [comment]
Added WIP so that I can squash the commits before we rebase the commits onto master (to keep the signature).

**Comment by leios** [comment]
Overall, it looks good. There still seem to be some errors on building certain esoteric languages, but I guess that is to be expected.

**Comment by julianschacher** [comment]
Yeah, Prism drops errors for Chip-8, TI-83 Basic, Factor and Whitespace since they aren't on supported languages (yet).

**Pull request merged**
