### PR TITLE
Fix links to not point to the old repository anymore and remove a file that shouldn't be here.

### PR DESCRIPTION
**Pull request by julianschacher**
Every instance of "leios/algorithm-archive" is being replaced with "algorithm-archivists/algorithm-archive".

### CODE REVIEW

**Comment by julianschacher** [comment]
@leios What's up with [version_control.md2](https://github.com/algorithm-archivists/algorithm-archive/blob/master/chapters/principles_of_code/version_control.md2)? Is this file important/used?

**Comment by leios** [comment]
@julianschacher That was a mistake. It can definitely be deleted. Thanks!

**Comment by julianschacher** [comment]
@leios Do you want to delete it or should I just include it in this PR?

**Comment by leios** [comment]
I think it's fine to add it to this one

**Comment by leios** [comment]
Should we leave a link to the discord server in the how to contribute chapter?

**Comment by julianschacher** [comment]
Why not? The discord server is the place the main AAA discussion happens. It's also nicer to write there about something, that would otherwise spam a PR. Like a discussion about a detail, etc.
Aside from that, it doesn't hurt to have more people on Discord. It shouldn't be a requirement of course, but it should be a good option.

**Pull request merged**
