### PR TITLE
Added EditorConfig for PHP from Symfony coding standard

### PR DESCRIPTION
**Pull request by MichalHanajik**
This is best to merge before other PHP PRs, so I can update code with this code style

### CODE REVIEW

**Comment by Gathros** [comment]
There you go.

**Comment by MichalHanajik** [comment]
Thanks! :)

**Comment by Butt4cak3** [comment]
You broke the alphabetical order in .editorconfig ;-(

**Comment by MichalHanajik** [comment]
O.o there was order? :(
Wanna fix me that? 😈

**Comment by Butt4cak3** [comment]
Yeah, there was order, but @julianschacher already broke it with his darn `[.emojic]` section. I'll just fix it whenever I touch the file anyway.

**Comment by julianschacher** [comment]
Ohh there was an order; missed that, sorry!

**Comment by PudottaPommin** [comment]
PHP style guide:

- PSR-2 standard
- global functions (set outside of classes) will be snake_case
- variables will be camelCase

**Pull request merged**
