### PR TITLE
Fixed infinite loop issue in "euclidean_example.py"

### PR DESCRIPTION
**Pull request by valdaarhun**
Fixes issue: #740

### CODE REVIEW

**Review by Saleniece — APPROVED** [review]

**Review by Amaras — APPROVED** [review]
That's basically what was needed, so thanks for that.

**Comment by valdaarhun** [comment]
I enjoyed working on this issue. Also, can I add my name to the CONTRIBUTORS.md file now or do I have to wait for the PR to get merged?

**Comment by Amaras** [comment]
You can do it now, at the risk of having to resolve conflicts later if another branch gets merged, or do it later, but that would mean opening another PR

**Comment by valdaarhun** [comment]
I guess I will do it after it gets merged. Thanks.

**Comment by leios** [comment]
It looks like you need to change the line numbers in the `euclidean_algorithm.md` to be from 11-27 for python. Once that is done, I am happy to merge!

**Comment by valdaarhun** [comment]
@leios Hi, I have changed the line numbers in `euclidean_algorithm.md`.

**Review by leios — APPROVED** [review]
Great! Thanks!

**Pull request merged**
