### PR TITLE
Added/fixed the C and C++ langs on the split operator method

### PR DESCRIPTION
**Pull request by rajdakin**
This pull request fixes the split operator method in C (as every code blocks were one line off), and adds the C++ implementation of that split operator method.

### CODE REVIEW

**Comment by Gathros** [comment]
This should be two different pull requests not one.

**Comment by leios** [comment]
This is actually just C++ code, so we should just modify the title to be exclusively C++, not C/C++

Still, we appreciate the submission!

**Comment by Gathros** [comment]
@leios no, there is also changes to the markdown that change the way c code is displayed.

**Comment by leios** [comment]
Oh, I see. Yeah, the line number changes should be a separate PR

**Comment by rajdakin** [comment]
Creating two other pull requests, one for each change.

**Pull request closed without merging**
