### PR TITLE
removing principles of code chapter, updating book

### PR DESCRIPTION
**Pull request by leios**
This PR addressed #33 . It removes the principle of code section (which was kinda aimless rambling anyway) and transforms it into mathematical background and data structures chapters, both of which will be continually updated with time.

It also moves other chapters to their relevant location.

As a note, this also hides work-in-progress sections from the site. In principle, these should all be hidden away in branches on my local fork, but I'll get to that soon. It also removed the personal note. It was basically a discussion about linux anyway, which is not relevant to algorithms.

### CODE REVIEW

**Comment by julianschacher** [comment]
For all the chapters that get moved and not deleted: we should maybe add redirects for them.

**Comment by leios** [comment]
yup, they should. I'll get the chapters consistent and then see about the redirects.

**Comment by julianschacher** [comment]
The restructuring with the latest changes and the redirects looks good :)
Do you plan to introduce more changes on this PR?

**Comment by leios** [comment]
Nope, that was it, I think. It's good for a review, if you are up for it.

**Comment by julianschacher** [comment]
`As a note, this also hides work-in-progress sections from the site.` what do you mean by that? There are still chapters that just say "coming soon".

**Comment by julianschacher** [comment]
I think we should always have the Title of each page in the biggest style i.e. `#`.
If you agree, `how_to_contribute.md`, `version_control.md`, `notation.md` and `differential_equations.md`, `physics_solvers.md`, `backward_euler_method.md` would need a change regarding the title.

**Comment by leios** [comment]
I think these latest commits fix those problems.

**Comment by julianschacher** [comment]
Everything seems fine, I have no more complains.

**Pull request merged**
