### PR TITLE
Racket implementation for Bubble Sort

### PR DESCRIPTION
**Pull request by Unlambder**
Added a racket implementation of Bubble Sort.
The bubbleSort function can be accessed by writing "(require "bubbleSort.rkt")" with the relevant file in the current directory.
I also put my name in Contributors.md since it seemed to be required.

### CODE REVIEW

**Comment by Butt4cak3** [comment]
Welcome, @Unlambder! There's not much I can say other than thanks for the contribution. You thought of pretty much everything.

I'm not sure whether we have a Racket developer who can properly review your code, so give it a few days time. If we can't find anyone, we'll probably just merge it anyway.

**Comment by jiegillet** [comment]
I read the code and, without prior knowledge of Racket, I think I made sense out of it, thanks for contributing.

Could you add some kind of main function with a test of the algorithm on a small list? This way someone without knowledge of the syntax (as myself) could run it and play around.

**Comment by Unlambder** [comment]
I made a [try it online](https://tio.run/##fVLBTsMwDL33K57EJRVM2hBCQoiv4FhxSBtvi/DcKslY@/XFzWBrAZHkYvvl@fklwTbvlMbxhq3sEHJUFIXpQvvhHaE@1jXTaxtSqVlHWy/zZAGYxkZasT3UzqIyXMJc62AYJtmlPbgs3xS@WAqH6AW/hXmBYFP@RMwW/1ObtzSdjVEbrzP1KtNq71IHeIZF9LJjwgS6gzZOex@hJ@0JojrPBY0EJ8K7tCcNbMp1I1gpG9jGBGI6kKQIGwiWA1k3IKoCchenvrU07VESBVU0OcakKqseZuuDEvHMmGqAidS04pbpAONC2ynVvY6S8yajKjUuD/nVolRALkWYgxf0GK6x7c9xWL5F9QufZf9xDeb2Mov6INnX6WdcRpps0KTK9bFjOyyeplfwOJoHbHQ/4gmbtdJ8Ag) link, will that be enough?

**Comment by jiegillet** [comment]
Is it hard or un-Racketty to include the test in the file? (I'm asking in full candor)
Is the try it online link a permanent resource?
We've considered using external resources before (I made a web app in Elm to demonstrate Euler method), but I think some people preferred the AAA to be self-sufficient. I'd like to wait and see other members' opinions on the question.

**Comment by julianschacher** [comment]
@Unlambder With the code submitted to the AAA, we want it to be possible to run locally on a machine. Therefor a main function kind of thing is useful since it sometimes calls different functions, etc. So I would suggest using a main function here as well.
The `try it online` link/thing is really cool tho and it would be a cool thing to do for different languages as well. Currently we don't do that, but it's a topic we should definitely discuss.
@jiegillet just saw your answer :)

**Comment by julianschacher** [comment]
I created an (issue)[https://github.com/algorithm-archivists/algorithm-archive/issues/167] for the discussion about the use of code-run-websites. I heavily support it.

**Comment by Unlambder** [comment]
I added an executable snippet to the file. To answer your question @jiegillet it's not that I find it un-Racketty or anything to include tests in the file, it's just that I didn't really know how i should include them.
 I hope this is enough, right now the file can be run directly from drRacket (maybe other environnements too) and loaded on a command line using (require).

**Comment by jiegillet** [comment]
Thanks for your last commit. I was able to run it on an online interpreter. Good enough for me. I'll merge the PR everyone is satisfied.

**Pull request merged**
