### PR TITLE
Fix warnings on size_t to int conversions on C++ Tree Traversal

### PR DESCRIPTION
**Pull request by ShadowMitia**

### CODE REVIEW

**Review by stormofice — APPROVED** [review]
Thanks for the PR!

Looks good to me.
[Tested with ` g++ -std=c++17 -Wall -Werror`, `g++ version 9.3.0`]

**Comment by Amaras** [comment]
> Looks good to me. [Tested with ` g++ -std=c++17 -Wall -Werror`, `g++ version 9.3.0`]

The objective is to compile with `-Wall -Wextra -Werror`, so could you please test this?

**Comment by stormofice** [comment]
Also works with `-Wextra`.

**Comment by Amaras** [comment]
Perfect, I'll merge this PR then

**Pull request merged**
