### PR TITLE
Dockerfile: set default to bash

### PR DESCRIPTION
**Pull request by ShadowMitia**
This sets a default to /bin/bash. The default being `sh` this should avoid issues for people running the docker with setting a shell.

This is easily overridden by passing the shell to the command as usual.

### CODE REVIEW

**Review by Amaras — COMMENTED** [review]
If you're going to do this, you also probably could change the PATH to include the Rust toolchain?

**Comment by ShadowMitia** [comment]
I'll double check but that only happens in the Github Action, no? When you launch the docker the rust toolchain is available (at least with bash). I'm just making sure it's not launched into `sh` by default.

**Review by Amaras — APPROVED** [review]
Ok, good for me, but you should probably remove the setup in the GH actions, then﻿

**Comment by ntindle** [comment]
Does the GH Actions still work with this?

**Comment by leios** [comment]
If the GH builds works here after updating it to main, it should be fine, right?

**Pull request closed without merging**
