### PR TITLE
Fix NOT-gate image to include inverter bubble

### PR DESCRIPTION
**Pull request by rweerasi**
The current image of the NOT Gate is currently incorrect, showing an image of a buffer. Adding the inverter bubble to the image fixes this minor issue.

### CODE REVIEW

**Comment by leios** [comment]
Hey @rweerasi was this for Hactoberfest? If so, I can add the tag.

**Comment by jiegillet** [comment]
As far as I know, the tag is not required to count...

**Comment by leios** [comment]
Oh, so I should just merge it then?

**Comment by rweerasi** [comment]
@leios I'd appreciate Hacktoberfest tag if it's not too late.

**Comment by leios** [comment]
I think you might need to sign up here: https://hacktoberfest.digitalocean.com/ for it to count

**Pull request merged**
