### PR TITLE
Update Rust implementations for Verlet algorithms

### PR DESCRIPTION
**Pull request by berquist**
This makes the changes outlined in https://github.com/algorithm-archivists/algorithm-archive/issues/257.

This is also the first Rust code I've ever written, so I don't know if it's idiomatic other than the implicit return. See [here](https://stackoverflow.com/a/51278038/3249688) for the approach.

### CODE REVIEW

**Comment by Butt4cak3** [comment]
You slipped (accidentally?) slipped some unrelated changes into this PR. I was about to approve this one, but I'll let @leios take a look at the grammar changes first.

**Comment by leios** [comment]
The grammar changes are fine.

**Comment by Butt4cak3** [comment]
Sorry for taking so long to get back to this. I took a break and forgot about the fact that there are still PRs open that require my attention. I will try to get this merged as soon as I get home from work today.

**Comment by Butt4cak3** [comment]
Alright. Took me another two days but I got around to reviewing and resolving the conflicts. Sorry for the long wait.

**Comment by Butt4cak3** [comment]
Alright. Still trying to get back into it properly. Took me another 2 days to get back to this but I got around to reviewing this and it's ready to merge. Sorry for making you wait this long.

**Pull request merged**
