### PR TITLE
Markdown formatting updates

### PR DESCRIPTION
**Pull request by berquist**
- Use a normal list in CONTRIBUTING, rather than HTML
- Update license copyright year
- Unfill text that doesn't change presentation

### CODE REVIEW

**Comment by leios** [comment]
These are all good changes. I cannot remember the purpose of the `<br>` tags, though...

**Comment by jiegillet** [comment]
Without the `<br>` all names were on the same line.

**Comment by leios** [comment]
Ah. Alright. I prematurely merged here then. Been a while since that happened.

So, we can just put a newline between each one instead of the `<br>` right?

**Comment by jiegillet** [comment]
No no, it should be good now, the PR replaced the `<br>` with `-` which should create a markdown list. It's an improvement!

**Comment by leios** [comment]
Ah, I should have checked this in remarkable before merging to be sure. Didn't think about it. Nice.

**Comment by jiegillet** [comment]
You can check in GitHub directly, within the PR, just click on view. Once it's merged in, you can just click on the file.

**Pull request merged**
