### PR TITLE
General implementation cleanup

### PR DESCRIPTION
**Pull request by stormofice**
This PR combines some easy syntactic fixes to standardize implementations for automatic testing and validation (in reference to #824 and #691).

These changes were done (see commit messages for more details):

- Huffman Encoding [java]: Move Huffman class to the top of the file
- Tree Traversal [java]: Move main method into Tree class
- Verlet Integration [java]: Move VerletValue class into Verlet class
- Monte Carlo [cpp]: Hardcode sample count (taken from julia implementation)

I tried to keep the formatting close to the original implementations.

### CODE REVIEW

**Comment by ntindle** [comment]
[lang: java] [lang: cpp]

**Comment by ntindle** [comment]
lol whoops though #847 was merged already

**Comment by ntindle** [comment]
[lang: java] [lang: cpp]

**Comment by ntindle** [comment]
[lang: cpp]

**Comment by ntindle** [comment]
[lang: c++]

**Review by Amaras — APPROVED** [review]
Looks all good to me.
I'd merge, but I'd like to get a second opinion.

**Comment by leios** [comment]
This looks good, but did the line numbers for the Monte Carlo and Tree Traversal chapters change? If so, the in-text code-blocks should be updated. It looks like it was done for Verlet and it doesn't seem to be necessary for Huffman. I was just double-checking before merging.

**Comment by stormofice** [comment]
The fixes for Tree Traversal and Monte Carlo did not require inserting code at the start of the file.
As the quoted functions in these chapters are at the beginning of the file, nothing needs to be changed as no code blocks got shifted downwards by inserting code above them.

However this is different for the other two implementations, which is why the numbers needed to be adjusted there but not for Tree Traversal / Monte Carlo.

[When the full code exmaple should be shown (like it is the case at the end of chapters), no line numbers are required in the md file and nothing needs to change there as well]

**Comment by leios** [comment]
Right, great! Thanks again. Happy to merge!

**Pull request merged**
