### PR TITLE
Runge-Kutta-Fehlberg Method

### PR DESCRIPTION
**Pull request by asuresh213**
Implemented the RK-Fehlberg variable step size method to solve ODEs of the form 
                                                          
                                             y' = f(t, y) 

with Initial conditions: 

                                  t in [a, b] and y(a) = alpha

### CODE REVIEW

**Comment by c252** [comment]
We don't accept implementations for things we don't have chapters for yet. We also already have a python implementation for monte carlo.

**Comment by Trashtalk217** [comment]
Hey, I noticed your pull request and I have a couple questions:
- Algorithm implementations are usually accompanied by a chapter that explains that algorithm. The Runge-Kutta-Fehlberg method seems mighty interesting but there is no chapter about it currently in the archive. What was your intention when putting it in the pull request?
- There already is a Monte Carlo implementation for python. Was there some mistake with git or is there something else? Please let me know.

I don't mean to sound hostile and all help is very appreciated, but this pull request has me a bit confused. So please let me know @asuresh213

**Comment by asuresh213** [comment]
@Trashtalk217 Oh, I apologize! I am new to this community and I wasn't sure how things worked! I understand better now. I'll look for chapters that do not have implementations yet, and try to contribute there! 

Thank you so much.

**Comment by leios** [comment]
@asuresh213 Feel free to join us for more discussion on discord: https://discord.gg/Pr2E9S6

**Comment by berquist** [comment]
Closing, since I think everyone has already come to a mutual understanding.

**Pull request closed without merging**
