### PR TITLE
Added Rust implementation of Jarvis March

### PR DESCRIPTION
**Pull request by Jess3Jane**
This is a fairly direct port of the Python implementation

### CODE REVIEW

**Comment by berquist** [comment]
@Jess3Jane poke.

**Comment by Jess3Jane** [comment]
Hey, sorry for the long delay, I wasn't checking my github!

**Comment by Jess3Jane** [comment]
Ah, it appears someone came along and implemented it again while I was away, I'll close this then.

**Comment by leios** [comment]
Sorry for all the trouble!

**Pull request closed without merging**
