### PR TITLE
WIP: Gaussian elimination in Fortran90

### PR DESCRIPTION
**Pull request by depate**
Initial commit. based on upstream master. intended to replace PR gaussian_fortran

### CODE REVIEW

**Comment by depate** [comment]
Maybe to document the progress:

I am struggling with initialisation of the array. Fortran has a different approach on how to fill up an array with values. Internal functions, like finding the index of max_val element, are row based. Therefore I tried to solve it with transponation of the array/matrix. Did not work out that good and created more bugs in the process. 

So still WIP.

**Comment by leios** [comment]
If there is a more fortran-esque way of doing this, I don't mind working with you to make that possible. Gaussian Elimination *must* be doable in Fortran. It's Fortran!

**Comment by fanninpm** [comment]
Perhaps you should try [wearing a blue tie?](https://james-iry.blogspot.com/2009/05/brief-incomplete-and-mostly-wrong.html)

**Comment by ntindle** [comment]
[lang: fortran]

**Comment by Amaras** [comment]
@depate Since this PR has not been updated significantly for 2 years, I will close this PR for now.

Feel free to re-open it if you wish to continue working on it, though :smiley:

**Pull request closed without merging**
