### PR TITLE
Euclid in MATLAB

### PR DESCRIPTION
**Pull request by MaxJWeinstein**
Putting in code for euclidSub and euclidMod in MATLAB. Also adding in name to the contributors file.

I apologize for any mistakes; this is my first time using git

### CODE REVIEW

**Comment by leios** [comment]
Hey @MaxJWeinstein , thanks for the PR. Would you be able to update the `euclidean_algorithm.md` file and adding the following lines:

```
{% sample lang="matlab" %}
[import:XX-XX, lang="matlab"](code/matlab/euclidean.m)
```
around lines 8, 42, and the end of the file? These are necessary for the code to render in the book. If you have trouble, let us know!

**Comment by jiegillet** [comment]
Hi @MaxJWeinstein I know I already approved you PR but for some reason GitHub is confused with `euclidean.md` and won't let me merge. Could you rename it to `euclidean_algorithm.md`?
Also, sorry I didn't catch it before, but you you get rid of  this line`### Matlab`? We are not using that anymore, it was a common source of mistakes and not necessary.

**Comment by jiegillet** [comment]
You renamed the wrong file. You needed to rename the `.md` file, not your matlab file. Also, not just the name needed to change, also the directory `chapters/algorithms/euclidean_algorithm/euclidean_algorithm.md` (notice the extra `algorithms`). 
Please double check that your matlab file name matches the one used in the `.md` file.

**Comment by MaxJWeinstein** [comment]
I forked the repository before the algorithm directory was added in. It might just be easier to get rid of this PR and submit a new one with the new directories added in

**Comment by jiegillet** [comment]
That's a possibility, but at this point, just creating the `algorithms` folder and move `euclidean_algorithm` inside it seems easier.

**Comment by MaxJWeinstein** [comment]
I'm using a mixture of Github's GUI, GitHub desktop, and sublime text to do this. I'm having trouble figuring out how to just change the file's name using these tools. Just do me a favor and close this pr

**Pull request closed without merging**
