### PR TITLE
Huffman Encoding Scratch Implementation

### PR DESCRIPTION
**Pull request by dovisutu**
I finally find a way to fix the buggy image... just set `transform: scale(1)`.

### CODE REVIEW

**Comment by leios** [comment]
I am impressed! Good work! We'll get to a review soon!

**Comment by jiegillet** [comment]
I can do a review, I also implemented (dynamic) Huffman encoding with Scratch (unshared). Is there an actual Scratch project? It would be easier to play with.

**Comment by dovisutu** [comment]
Yeah, I shared it (with extra interacting part which is a simple *enter-text-and-say-result* loop). [The link](https://scratch.mit.edu/projects/389604255/) is already in the chapter.

Maybe drawing the tree out can be better, but I didn't implement it partially because I didn't have enough time. Anyway, that can be done independently without revisiting the chapter and code.

**Comment by TimothyJu1985** [comment]
TimothyJu1985 archived:false

**Comment by leios** [comment]
I am unfortunately not a scratch master like @jiegillet, but can take a look at this, if needed. Let me know!

**Comment by dovisutu** [comment]
Hi, is the review going on?

**Review by leios — APPROVED** [review]
At this stage, I checked the project and it looks good! The code also looks good, so I am happy to give this a positive review!

Sorry again for the delay!

**Pull request merged**
