### PR TITLE
stack and queue in c

### PR DESCRIPTION
**Pull request by c252**
I implemented a stack and queue in c, James told me it was okay even though the section isn't open for code contribution.

### CODE REVIEW

**Comment by leios** [comment]
I'll be updating this section this weekend (hopefully), so we'll hold off on merging this until that is done.

**Comment by binarydinosaur252** [comment]
sounds good.

**Comment by binarydinosaur252** [comment]
I will put in some error handling for the size. One problem is that I don't think you can have dynamically sized arrays in c. I think my queue implementation could also be more efficient though.

(should I close this PR, commit the changes and then make a new one)

**Comment by Gathros** [comment]
No, you can just commit to the same branch and the PR updates. Also you use `malloc` and resize it with `realloc` to make a dynamically sized array in c.

**Comment by Gustorn** [comment]
Of course you can have dynamically sized arrays in C, it wouldn't be a very useful language otherwise :) You just need to do it by hand with `malloc`

**Pull request closed without merging**
