### PR TITLE
Adding a C Monte Carlo implementation.

### PR DESCRIPTION
**Pull request by Gathros**

### CODE REVIEW

**Comment by Gathros** [comment]
@jiegillet I dont mind either way.

**Comment by leios** [comment]
@jiegillet I added in a variable radius for monte carlo because with the `radius` variable, the formula in the end makes more physical sense. I was afraid that just leaving it as 1 would make it harder to understand what we are actually doing.

That said, I am fine with either way.

**Comment by jiegillet** [comment]
Leaving `radius` in the expression for `in_circle` makes sense if you want to show the meaning, but using a value of `0.5` doesn't, since precision is lost. Just use `1`, I don't think it makes it harder to understand.

**Comment by leios** [comment]
Yeah, I don't disagree. We could also just set the radius function parameter `function in_circle(pos_x, pos_y, radius = 1)` as a default unless otherwise specified.

**Comment by leios** [comment]
thanks a bunch, sorry it took me so long!

**Pull request merged**
