### PR TITLE
Haskell: added DFT and re-wrote FFT

### PR DESCRIPTION
**Pull request by jiegillet**
Added previously missing DFT and re-wrote FFT, I was quite unhappy with it, it's better now.

Yay #hacktoberfest #394!

### CODE REVIEW

**Comment by leios** [comment]
So... I don't know if these count as hactoberfest because it's not yet october... But I appreciate them anyway!

**Comment by jiegillet** [comment]
Oh no!!! It’s not October yet?! 
Feel free to reject them then :’(

**Comment by leios** [comment]
I mean... You could close and re-submit? That's your call.

**Comment by jiegillet** [comment]
Maybe I’m a hipster and I was coding for hacktoberfest before it was cool?

**Comment by leios** [comment]
I am having some trouble reading this one. It's because of my limited haskell experience, though. I'll sift through it soon (Unless someone with more haskell exp. wants to take over).

**Comment by jiegillet** [comment]
I'm happy to walk you through it if you want

**Comment by leios** [comment]
I might need that. I am getting better at haskell, but I am still a bit behind.

**Pull request merged**
