### PR TITLE
Added Brainfuck implementation of Bogosort

### PR DESCRIPTION
**Pull request by DanielMowitz**

### CODE REVIEW

**Comment by DanielMowitz** [comment]
A little Backstory: 
When Hacktoberfest rolled around I was reminded of adding some code to this project last year. I also remembered that I still had'nt finished bf bogo. It just so happened that a few friends and I planned a week of silence and meditation, during which I utilized my inner peace to write the heart and soul of this algorithm, the random function. After about two weeks the rest was done, so here we are.

**Comment by DanielMowitz** [comment]
Just wanted to ping this one and ask if there's something left for me to do on this PR for it to be merged? I don't really get the Travis error.

**Comment by leios** [comment]
I am sorry it has taken me so long to get to this. We know about the travis error and are currently waiting on someone to review this. Sorry for the wait!

**Comment by ntindle** [comment]
[lang: brainfuck]

**Comment by Amaras** [comment]
Sorry, but we can't accept sorting PRs for now.

**Pull request closed without merging**
