### PR TITLE
Added Bubblesort in Chip-8 assembly

### PR DESCRIPTION
**Pull request by theinventor13**
This code in and of itself is a runnable example, which displays an array of 12 random bytes before being sorted, and after
https://massung.github.io/CHIP-8/ tested using this emulator

### CODE REVIEW

**Comment by leios** [comment]
I have no idea how to review this one... Maybe @Gathros ?

**Comment by Liikt** [comment]
I'll take a look at it, but I can't promise anything.

**Comment by leios** [comment]
@theinventor13 It should be quick, then. The review is just a check to make sure the code functions and follows appropriate style guidelines; however, in this case, we are probably more concerned about functionality than style.

**Comment by leios** [comment]
More info on how to do that can be found here: https://github.com/algorithm-archivists/algorithm-archive/wiki/How-to-Contribute#step-33---adding-code-to-your-aaa-repo

**Comment by Liikt** [comment]
yes it works now :+1:

**Pull request merged**
