### PR TITLE
Bubble Sort VB .net Implementation

### PR DESCRIPTION
**Pull request by dovisutu**

### CODE REVIEW

**Comment by leios** [comment]
Hey @dovisutu Sorry about the wait, we need someone to review this PR and unfortunately do not have a local expert in VB. We are waiting on a review before merging this one.

**Comment by dovisutu** [comment]
Well... Actually I'm doubted about the Realizing of Bubble Sort, because the input array is so different.
in C++,C and a lot of languages: [An integer array]
`int input[] = {1, 45, 756, 4569, 56, 3, 8, 5, -10, -4};`
in D: [A random float array]
`auto input = generate!(() => uniform01!float).take(10).array;`
in Julia and some other languages: [A float/double array]
`a = [1., 3, 2, 4, 5, 10, 50, 7, 1.5, 0.3]`
in Matlab: [A random integer array]
`array = floor(rand(1, 7) * 100);`
Anyhow, in my next commit, I'll change my reference from C++ [Because I can read it easier] to Julia [Leios's Standard?]

**Comment by dovisutu** [comment]
BTW, there's a VB **.net** document [here](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/), because I'm implementing bubble sort, this may be helpful.

**Comment by dovisutu** [comment]
BTW, there's a vb __.net__ document [here](https://docs.microsoft.com/zh-cn/dotnet/visual-basic/), since I'm implementing bubble sort, this may be work.

**Comment by ntindle** [comment]
[lang: vb]

**Comment by Amaras** [comment]
Sorry this took so long, but we don't accept sorting algorithm PRs any more.
I'm closing this.

**Pull request closed without merging**
