### PR TITLE
Fixing Huffman Encoding edge case failure for assembly x64

### PR DESCRIPTION
**Pull request by Gathros**

### CODE REVIEW

**Comment by leios** [comment]
Is anyone actually able to review this? If not, I am happy to run it locally and try to figure it out, but I would need a little help figuring out how to do that.

**Comment by ntindle** [comment]
[lang: asm]

**Review by stormofice — APPROVED** [review]
The code looks good to me and it produces the correct output. Thanks!


[If anyone wants to test this themselves, change the `text` variable to something like `aaaaaaaaaa` and compile it with `gcc -no-pie huffman.s`]

**Comment by stormofice** [comment]
I  think that [code] line length should be checked by a CI task / GitHub action or something similar in the future, so I think we can merge this one (and fix the line length later on with other ones that will fail when this gets enforced).

**Comment by ntindle** [comment]
Imo we should aim for the editor to support wordwrap rather than have the maintainers be responsible for checking line length

**Comment by stormofice** [comment]
I created an issue (see #962) to separate the discussion about long lines and unblock this PR.

**Comment by Amaras** [comment]
Since this has been approved and a specific issue has been opened, I'm merging this in

**Pull request merged**
