### PR TITLE
Declare "noninteractive" environment variable globally in Dockerfile

### PR DESCRIPTION
**Pull request by ShadowMitia**

### CODE REVIEW

**Comment by berquist** [comment]
Is #1021 an accidental incomplete duplicate?

**Comment by berquist** [comment]
My only concern is that this will be annoying for someone using this image as a dev container.  Is there a way to set image build args for dev containers?

**Comment by ShadowMitia** [comment]
ARGs are only available during builds, so it shouldn't interfere afterwards. And you can override them.

**Review by berquist — APPROVED** [review]
Right, that slipped my mind.  All seems good.

**Pull request merged**
