### PR TITLE
Adding C# to the build system (using the Mono toolchain)

### PR DESCRIPTION
**Pull request by Amaras**
This is a PR to add C# to our build system, making sure we have a common ground.
I see we have the dotnet sdk, but I could not find the command to compile using it, don't hesitate to close this PR if you give me the proper way.

Because I used Mono, there were a few changes in two files, as Mono doesn't allow functions inside functions, apparently.

This follows from #1011, but might need to be merged before.

### CODE REVIEW

**Comment by Amaras** [comment]
Right... @ntindle or @ShadowMitia, do I need to separate the Docker stuff from the SCons stuff for the build to pass?

**Comment by ntindle** [comment]
Docker should probably go in first. I can't remember the exact repo ci we used but if we did it right, it won't use the dockerfile you provide here but the one on the base branch

**Comment by ShadowMitia** [comment]
FYI: for dotnet you can use this as reference: https://github.com/SebLague/Chess-Challenge/discussions/3
But it could be good to support both? I don't really know C# ecosystem well enough.
I don't have an opinion on which one is better to use.

**Comment by Amaras** [comment]
There we go, everything builds :)
If someone wants to review it, please do so we can move on

**Review by ShadowMitia — APPROVED** [review]
LGTM

**Pull request merged**
