### PR TITLE
Add bubble sort algorithm in R language

### PR DESCRIPTION
**Pull request by graue70**

### CODE REVIEW

**Comment by graue70** [comment]
Sorry. I didn't check for other PRs before committing.

I reopened it because both #636 and #576 have code issues.

**Comment by c252** [comment]
I think we should use this PR because the authors of #636 and #576 seem to have lost interest in their PRs.

**Comment by leios** [comment]
Cool. Thanks @jiegillet !

**Comment by leios** [comment]
Oh, and @graue70 for submitting! Good work!

**Pull request merged**
