### PR TITLE
Update JavaScript Jarvis March to use points from Graham Scan

### PR DESCRIPTION
**Pull request by berquist**
This uses the points from https://github.com/algorithm-archivists/algorithm-archive/blob/4313e7eb3d2faa152590c631d180d06a5c85f46d/contents/graham_scan/code/julia/graham.jl#L50

### CODE REVIEW

**Comment by leios** [comment]
I think @jiegillet did something with the Haskell code such that these numbers were not "magic," but instead pulled from some distribution, but I don't remember the trick. I think he just randomly picked a distribution from within a circle, but I don't remember how he knew which points should be excluded.

I can look into this in a bit.

Thanks a bunch for all the PR work recently!

**Comment by berquist** [comment]
I see. If we can find out, then that information should be at the end of the chapter. Of course, hold off on all the related PRs until we get that information.

**Comment by jiegillet** [comment]
I made the points this way:

```haskell
let pts = [(x,y) | x<-[-5..5], y<-[-5..5], x^2+y^2<=5^2]
```

which means, take all points on a square grid from (-5,-5) to (5,5) and keep the ones inside or on a circle of radius 5.

**Comment by ntindle** [comment]
[lang: javascript]

**Review by Amaras — APPROVED** [review]
LGTM, I'll merge this soon

**Pull request merged**
