### PR TITLE
Added EditorConfig rule for Matlab and Racket source files

### PR DESCRIPTION
**Pull request by Butt4cak3**
Just that.

### CODE REVIEW

**Comment by Butt4cak3** [comment]
Wait, I'll add Racket files too.

**Comment by leios** [comment]
I guess we should have people who know matlab and racket to talk about this? I don't see any reason it would be a problem, though, so I'll approve the PR in a day if there is no discussion.

@jiegillet @VikingScientist @Unlambder

**Comment by jiegillet** [comment]
No objection for matlab

**Comment by Butt4cak3** [comment]
@Leios I looked at the Matlab and Racket code people submitted. I didn't make the indentation rules up :p

**Comment by Butt4cak3** [comment]
I took the existing Matlab and Racket code examples and derived the rules from those. It's in line with what we already have. I don't know why nobody approves this PR to be honest.

**Comment by leios** [comment]
Approved

**Pull request merged**
