### PR TITLE
Renamed some language code dirs for consistency

### PR DESCRIPTION
**Pull request by Butt4cak3**
Some languages, namely JavaScript and Haskell had code directories both called "javascript" and "js" or "haskell" and "hs" respectively. That kind of bothered me for no practical reason, so I changed it.

Because the code directories of all other languages are named after the language, not the file extension (e. g. "julia" rather than "jl"), I went for "javascript" and "haskell" over "js" and "hs".

I also renamed "R" to "r" because everything else is lowercase.

One thing I thought about chaning, but didn't, are the C# code directories. They are called "cs", after the C# file extension. I thought about renaming them to "csharp" to go with the theme. What are your thoughts on it?

### CODE REVIEW

**Comment by Gustorn** [comment]
I vote for `csharp` as well, it's just more readable.

**Comment by julianschacher** [comment]
csharp sounds good

**Comment by leios** [comment]
Yeah, this is good. Merging.

Should we also note what languages correspond to different directories somewhere?

**Comment by Butt4cak3** [comment]
It's not a bad idea, but I don't know where we could note that. I guess as long as the dev team knows the naming scheme we're fine for now.

**Pull request merged**
