### PR TITLE
Add Python3 code to Verlet

### PR DESCRIPTION
**Pull request by HugoGranstrom**
There was already Python2 code included in the article but as newcomers to Python should learn Python3 it makes sense to also add Python3 code. Hope my code makes sense. 
In the last example I left Stormer-Verlet out because it is just Classical Verlet but you calculate the velocity but you don't use it in this example with the falling ball.

### CODE REVIEW

**Comment by HugoGranstrom** [comment]
Alright, thank you for the review :-). I'm away from home for a couple of days and I don't have my laptop with me so I can fix this on Wednesday. Is that ok?

**Comment by leios** [comment]
Yeah, get to it when you have time! Thanks for contributing!

**Comment by HugoGranstrom** [comment]
@leios thank you sir :-) Hopefully I won't be leaving AAA for a long time ;-)

**Comment by HugoGranstrom** [comment]
I just noticed that the old python2 version of verlet was changed yesterday to python3. I guess I should closed this one then?

**Comment by Butt4cak3** [comment]
Oh no, you're right. I'm so sorry. I totally didn't think of that. I'm sure you will find another cool algorithm you can implement! The timing was just a bit unfortunate because we just made a big decision regarding Python. I hope that's okay.

**Pull request closed without merging**
