### PR TITLE
Adding Formatting to File Names

### PR DESCRIPTION
**Pull request by CDsigma**
Some programs use multiple files and have the title of the file above the code. Currently there is no formatting on these titles.

I added in '#####' before these titles which I think looks a little nicer.

This might just be a personal preference though so I understand if it isn't merged.

### CODE REVIEW

**Comment by leios** [comment]
I agree with this. It's a bit nicer. I'll leave it up for a bit so people can see it, though.

**Comment by jiegillet** [comment]
I don't mind.

**Comment by jiegillet** [comment]
Are these changes exhaustive?

**Comment by leios** [comment]
I think so, but haven't checked thoroughly yet. There are not too many programming languages that require multiple files for their implementations.

**Comment by jiegillet** [comment]
I'm thinking of blocking this PR until we come up with 

1. A Script that finds and replace such occurrences (bash or Python, I guess)
2. A place in the AAA where we describe the new format.

Does it sound OK? I think we need both of these before we merge this.

**Comment by julianschacher** [comment]
I'm in favor of these changes. The filenames look better in bold text.

**Pull request merged**
